### ISSUE TITLE
'Could not set videomode' for Kinect v2 on Ubuntu

### ISSUE THREAD

**Issue by luyuechao** [pamela-project/slambench1#1]
I'm using libfreenect2 driver for kinect v2 on Ubuntu 14.04.
It's OK to run NiViewer2 suing the OpenNI2 API to access RGB-D.
While using slambench, I installed all required dependency and compiled without error.
 I still got the following error while runing:

[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 16 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @4:5 with serial 000455760447
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 16 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @4:5 with serial 000455760447
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20_16384 ir: 60_8_33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
*_Could not set videomode**
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] releasing usb interfaces...
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] already closed, doing nothing

Every implementation (C++, OpenMP, OpenCL) has the same error.
The lamp of kinect v2 turn on for 2 seconds and turn off.
I thing there must be some setup difference between kinect v1 and v2. 
Is there anything I should setup in the reader.cpp file?
Thank you!

**Comment by bbodin** [comment]
If there is a modification to do, this is probably in the interface.h file. We don't have any Kinect v2 to test, but I suppose that to initialize a Kinect2, you might need to change this part :

```
            openni::VideoMode newDepthMode;
            newDepthMode.setFps(fps == 0 ? 30 : fps);
            newDepthMode.setPixelFormat(openni::PIXEL_FORMAT_DEPTH_1_MM);
            newDepthMode.setResolution(640,480);

            rc = depth.setVideoMode(newDepthMode);

....

            openni::VideoMode newRGBMode;
            newRGBMode.setFps(fps == 0 ? 30 : fps);
            newRGBMode.setPixelFormat(openni::PIXEL_FORMAT_RGB888);
            newRGBMode.setResolution(640,480);

            rc = rgb.setVideoMode(newRGBMode);


```

I will try to see if I can find one to test.

**Comment by luyuechao** [comment]
Thank you for you advice. I'll have a try and give you feedback:-)
