### ISSUE TITLE
How to understand the `kernel timings` log file

### ISSUE THREAD

**Issue by hanm2019** [pamela-project/slambench1#14]
I run this benchmark  with`KERNEL_TIMINGS=1 ./build/kfusion/kfusion-benchmark-cpp -s 4.8 -p 0.34,0.5,0.24 -z 4 -c 2 -r 1 -k 481.2,480,320,240 -i  living_room_traj2_loop.raw -o  benchmark.2.cpp.log 2> kernels.2.cpp.log` to measure the kernel run time and get the log file successfully, but I can not understand this log file

```
mm2metersKernel 228800 76800
bilateralFilterKernel 18824084 76800
bilateralFilterKernel 200285 19200
halfSampleRobustImageKernel 43592 4800
depth2vertexKernel 587803 76800
vertex2normalKernel 1094186 76800
depth2vertexKernel 148231 19200
vertex2normalKernel 273021 19200
depth2vertexKernel 36672 4800
vertex2normalKernel 73790 4800
trackKernel 234179 4800

```

I know the `mm2metersKernel`,`bilateralFilterKernel`, `bilateralFilterKernel` are the name of kernels, but can not find some explain about the two number behind the kernel name

**Comment by bbodin** [comment]
First column is the execution time (I believe in ns), second column is the data size (in number of values) that this kernel had to consider. When playing with algorithmic parameters you might change the data size, so we keep track of this information. 
You can check the function that produce this output, for example for the CPP implementation it is a preprocessing macro named TOCK.

**Comment by hanm2019** [comment]
thanks~
