### ISSUE TITLE
Is it possible to operate on RGB-D SLAM Dataset from TUM?

### ISSUE THREAD

**Issue by celinachild** [pamela-project/slambench1#2]
I would like to operate slambench on RGB-D SLAM dataset from TUM and get some evaluation data.
(http://vision.in.tum.de/data/datasets/rgbd-dataset)

is it possible?

**Comment by luinardi** [comment]
Hello, in the next release we will be providing the tools to access the TUM RGB-D dataset out-of-the-box from SLAMBench like in this paper: 
http://arxiv.org/abs/1509.04648
Stay tuned!
