### ISSUE TITLE
ICL NUIM Living Room 'lr kt3' large errors 

### ISSUE THREAD

**Issue by noraabiakar** [pamela-project/slambench1#7]
Running SLAMBench on the 3rd ICL-NUIM dataset results in large errors (calculated using the checkPos.py script)

./kfusion-benchmark-cpp -i ../images/living_room_traj3_loop.raw -s 5.0 -p 0.2685,0.5,0.4 -z 4 -c 2 -r 2 -k 481.2,480,320,240 > benchmark3.log

Results:
Runtimes are in seconds and the absolute trajectory error (ATE) is in meters.
The ATE measure accuracy, check this number to see how precise your computation is.
Acceptable values are in the range of few centimeters.
                 ATE 	Min : 0.000000 	Max : 1.013398 	Mean : 0.443021 	Total : 549.34550777
         acquisition 	Min : 0.000253 	Max : 0.000965 	Mean : 0.000312 	Total : 0.38802896
         computation 	Min : 0.113514 	Max : 1.444738 	Mean : 0.276759 	Total : 343.73466516
         integration 	Min : 0.000000 	Max : 1.033722 	Mean : 0.060491 	Total : 75.13015601
       preprocessing 	Min : 0.045917 	Max : 0.107041 	Mean : 0.058401 	Total : 72.53400498
          raycasting 	Min : 0.000000 	Max : 0.366428 	Mean : 0.127452 	Total : 158.29547959
           rendering 	Min : 0.000535 	Max : 0.264892 	Mean : 0.033593 	Total : 41.72202484
           total     	Min : 0.114366 	Max : 1.445859 	Mean : 0.310664 	Total : 385.84471896
            tracking 	Min : 0.005844 	Max : 0.058434 	Mean : 0.030415 	Total : 37.77502458

Is there an explanation for this? 
Thank you for your help!

**Comment by bbodin** [comment]
In the regression test we run this dataset using make 3.cpp.log 
You can have a look at the output through this webpage; https://travis-ci.org/pamela-project/slambench
The results you obtain are different, could you try to use make 3.cpp.log to confirm those values.

**Comment by noraabiakar** [comment]
Thank you for your quick reply. I started again from scratch. I cleared everything and used make 3.cpp.log 
This time around I get slightly better results: total ATE of 193m compared to your 155m. I can not explain the discrepancy here. It seems a bit too much to blame on floating point errors. 
I was able to reproduce the result for dataset2 though. So what I am wondering is the following: Is there anything special about dataset3? even 155m is a bit large compared to your 18m for dataset2. And is there any reason you can think of for why the algorithm would produce different results on my platform? 
Thank you again! 

--------------------
Results for dataset 3:

         ATE  Min : 0.000000  Max : 0.625946  Mean : 0.156214   Total : 193.70504175
         acquisition  Min : 0.000278  Max : 0.000785  Mean : 0.000370   Total : 0.45959000
         computation  Min : 0.113209  Max : 0.946405  Mean : 0.284552   Total : 353.41412000
         integration  Min : 0.000000  Max : 0.636795  Mean : 0.063202   Total : 78.49638200
         preprocessing  Min : 0.045284  Max : 0.099378  Mean : 0.057979   Total : 72.00950800
         raycasting  Min : 0.000000  Max : 0.317351  Mean : 0.132559   Total : 164.63801300
         rendering  Min : 0.000541  Max : 0.328894  Mean : 0.034961   Total : 43.42180000
         total      Min : 0.114079  Max : 1.181560  Mean : 0.319884   Total : 397.29550400
         tracking  Min : 0.006282  Max : 0.052717  Mean : 0.030813   Total : 38.27032300

**Comment by bbodin** [comment]
OK, in the case of lr3, floating point "can" be a reason. 
We witnessed discrepancy in the past, and the lr3 dataset is particularly sensible, at least with kfusion and the parameters we specified. Typically what happens is that if the tracking is lost for at least one frame, then the entire trajectory is wrong (and the ATE then is dramatically high).
Depending of your objective I guess there is multiple solutions. You could either not using lr3, either I could provide slightly better parameters for this trajectory.
Could you tell us which architecture you are using ? I would be interested to reproduce the numbers.
