### ISSUE TITLE
Can 2D slam(like gmapping,karto) use this to evaluate result?How can I do it?

### ISSUE THREAD

**Issue by gongyue666** [pamela-project/slambench1#9]

**Comment by bbodin** [comment]
This is an interesting point, currently it does not, even the most recent version of SLAMBench (https://github.com/pamela-project/slambench2) which is quiet modular would not work in 2D out of the box. However I don't see anything that would stop that to happen.

To reproduce experiments for those 2D SLAM systems with SLAMBench2, the major change would be to define what is a 2D ground truth and 2D position and map (in addition with implementing a SLAMBench API for those systems). Even though I guess a hack could be to define everything as 3D with Z=0.

**Comment by gongyue666** [comment]
Thx so much~
